### ISSUE TITLE
Is Your Project Still Active?

### ISSUE THREAD

**Issue by davegoopot** [beelogger/RPi-Beelogger#3]
Hello, I'm just starting my own project to electronically monitor bee hives. How is your project going?

Regards,

Dave.

**Comment by JavanXD** [comment]
Hi Dave, 

I don't think this project will be actively developed any further. 

But have a look at HoneyPi.de. We are developing an open source Raspberry Pi firmware with connections to ThingSpeak, CSV files and soon MQTT for Grafana. We are already supporting many sensors. Help with further development would be great, of course.

GitHub: https://github.com/Honey-Pi
